# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weather_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weather_app

  target 'weather_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNSnackbar', :path => '../node_modules/react-native-snackbar'

  end

  target 'weather_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'weather_app-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for weather_app-tvOS

  target 'weather_app-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'React', path: '../node_modules/react-native', subspecs: [
  'ART',
]
